[project]
name = "proxy-server"
version = "0.1.1"
description = "A simple proxy server implemented in Python."
readme = "README.md"
requires-python = ">=3.13,<=3.14"
license = { text = "MIT" }
dependencies = [
    "fastapi==0.131.0",
    "mysql-connector==2.2.9",
    "pydantic==2.12.5",
    "requests==2.32.5",
    "uvicorn==0.41.0",
]

[dependency-groups]
dev = [
    "ruff==0.15.2",
    "bandit==1.9.3",
    "pyright==1.1.408",
]

[tool.bandit]
exclude_dirs = [".venv"]
